hydra:
  AdminUrl: "http://localhost:4445"
  PublicUrl: "http://localhost:4444"

database:
  driver: "mysql"
  dbname: "go-oauth"
  username: "root"
  password: ""
  host: "localhost"
  port: "3306"
  max_lifetime: 7200
  max_open_conns: 150
  max_idle_conns: 50

server:
  port: "3000"
  secret: "jdnfksdmfksda"
  #release | debug
  mode: "debug"